CREATE TABLE SMSBUMP.OTP (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL,
otp TEXT NOT NULL,
date_issued DATETIME NOT NULL
)

CREATE TABLE SMSBUMP.Attempts (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL,
telephone VARCHAR(255) NOT NULL,
otp TEXT NOT NULL,
date_issued DATETIME NOT NULL
)